# A simple store configuration: we use one database for everything
# This is equivalent to the old way of configuring the store for tests
# by just setting the environment variable THEGRAPH_STORE_POSTGRES_DIESEL_URL

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph-node:5432/graph-node"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = ["default"]

[chains]
ingestor = "default"

[chains.arbitrum-one]
shard = "primary"

# archive node test: 
#   curl https://arbitrum.llamarpc.com -X POST -H "Content-Type: application/json" --data '{"method":"eth_getBalance","params":["0x82af49447d8a07e3bd95bd0d56f35241523fbab1", "0x55"],"id":1,"jsonrpc":"2.0"}'
provider = [
  { label = "erpc1", url = "${ERPC_PRIVATE_ENDPOINT_1}", features = ["archive"] },
  { label = "erpc2", url = "${ERPC_PRIVATE_ENDPOINT_2}", features = ["archive"] },
  { label = "erpc3", url = "${ERPC_PRIVATE_ENDPOINT_3}", features = ["archive"] },
  { label = "erpc4", url = "${ERPC_PRIVATE_ENDPOINT_4}", features = ["archive"] }
]
