global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['erpc-monitoring:9090']

  - job_name: 'erpc'
    static_configs:
      - targets: ['erpc-proxy:4001']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093